//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webdavSrvHost {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webdavSrvHost.Res1", typeof(Res1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;D:lockinfo
        ///	xmlns:D=&quot;DAV:&quot;&gt;
        ///	&lt;D:lockscope&gt;
        ///		&lt;D:exclusive/&gt;
        ///	&lt;/D:lockscope&gt;
        ///	&lt;D:locktype&gt;
        ///		&lt;D:write/&gt;
        ///	&lt;/D:locktype&gt;
        ///	&lt;D:owner&gt;
        ///		&lt;D:href&gt;DESKTOP-FP4SN02\user&lt;/D:href&gt;
        ///	&lt;/D:owner&gt;
        ///&lt;/D:lockinfo&gt;.
        /// </summary>
        internal static string lockReq {
            get {
                return ResourceManager.GetString("lockReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;D:prop
        ///	xmlns:D=&quot;DAV:&quot;&gt;
        ///	&lt;D:lockdiscovery&gt;
        ///		&lt;D:activelock&gt;
        ///			&lt;D:locktype&gt;
        ///				&lt;D:write/&gt;
        ///			&lt;/D:locktype&gt;
        ///			&lt;D:lockscope&gt;
        ///				&lt;D:exclusive/&gt;
        ///			&lt;/D:lockscope&gt;
        ///			&lt;D:depth&gt;0&lt;/D:depth&gt;
        ///			&lt;D:owner&gt;
        ///				&lt;D:href&gt;DESKTOP-FP4SN02\user&lt;/D:href&gt;
        ///			&lt;/D:owner&gt;
        ///			&lt;D:timeout&gt;Second-3600&lt;/D:timeout&gt;
        ///			&lt;D:locktoken&gt;
        ///				&lt;D:href&gt;opaquelocktoken:e9962eb2-5a53-49df-830a-14db5a7899fc.088101d7ad90a509&lt;/D:href&gt;
        ///			&lt;/D:locktoken&gt;
        ///			&lt;D:lockroot&gt;
        ///				&lt;D:href&gt;http: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LockRes {
            get {
                return ResourceManager.GetString("LockRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;D:multistatus xmlns:D=&quot;DAV:&quot;&gt;&lt;D:response&gt;&lt;D:href&gt;http://localhost/&lt;/D:href&gt;&lt;D:propstat&gt;&lt;D:status&gt;HTTP/1.1 200 OK&lt;/D:status&gt;&lt;D:prop&gt;&lt;D:getcontenttype/&gt;&lt;D:getlastmodified&gt;Sun, 19 Sep 2021 19:34:24 GMT&lt;/D:getlastmodified&gt;&lt;D:lockdiscovery/&gt;&lt;D:ishidden&gt;0&lt;/D:ishidden&gt;&lt;D:supportedlock&gt;&lt;D:lockentry&gt;&lt;D:lockscope&gt;&lt;D:exclusive/&gt;&lt;/D:lockscope&gt;&lt;D:locktype&gt;&lt;D:write/&gt;&lt;/D:locktype&gt;&lt;/D:lockentry&gt;&lt;D:lockentry&gt;&lt;D:lockscope&gt;&lt;D:shared/&gt;&lt;/D:lockscope&gt;&lt;D:locktype&gt;&lt;D:write/&gt;&lt;/D:locktype&gt;&lt;/D:l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropfindRes {
            get {
                return ResourceManager.GetString("PropfindRes", resourceCulture);
            }
        }
    }
}
